models:
  - name: days_occupied_per_month
    columns:
      - name: listing_id
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number 
      - name: neighbourhood
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
      - name: property_type
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar
      - name: calendar_month
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date    
      - name: price
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1000000000
      - name: days_occupied
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number

  - name: monthly_host_revenue
    columns:
      - name: calendar_month
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date  
      - name: neighbourhood
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar                
      - name: avg_revenue_per_host
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1000000000
  - name: monthly_neighborhood_analysis
    columns:
      - name: neighbourhood
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar    
      - name: property_type
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: varchar        
      - name: calendar_month
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: date  
      - name: avg_price
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 1000000000
      - name: avg_rating
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100
